### ISSUE TITLE
Issues to address 4/23/15

### ISSUE THREAD

**Issue by lphelps7** [WEB290-2015/missionpawncapstone#11]
SEO analysis addressing issues
Meta tags - Lizabeth
Meet with Hopper about server--Kelly
Look over content for consistency--Lindsay
Photoshop ladders from picture, community service image-Lindsay
Robot.txt--Kenita
Sight map--Kenita
Working on presentation powerpoint-Brian

Meet with Tummons friday the 24th

**Comment by lphelps7** [comment]
Lizabeth - Meta tags were created in wordpress, also an icon added.

**Comment by keeis2coo** [comment]
Robot.txt and sight map were created...I will need to recreate them when we move the site to the new server.
